version = 0.1

[default]
[default.global.parameters]
stack_name = "randomno-dev"
s3_bucket = "rajnish-demo-learning"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "sam-lambda-learning"
template_file = "template-export.yaml"
region = "ap-south-1"
disable_rollback = true
parameter_overrides = {}
image_repositories = []

[default.package.parameters]
stack_name = "randomno-dev"
s3_bucket = "rajnish-demo-learning"
output_template_file = "packaged-template-dev.yaml"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[preprod]
[preprod.global.parameters]
stack_name = "randomno-preprod"
s3_bucket = "rajnish-preprod-learning"

[preprod.build.parameters]
cached = true
parallel = true

[preprod.validate.parameters]
lint = true

[preprod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "sam-lambda-learning-preprod"
template_file = "template-preprod.yaml"
region = "ap-south-1"
disable_rollback = true
parameter_overrides = {}
image_repositories = []

[preprod.package.parameters]
stack_name = "randomno-preprod"
s3_bucket = "rajnish-preprod-learning"
output_template_file = "packaged-template-preprod.yaml"

[preprod.sync.parameters]
watch = true

[preprod.local_start_api.parameters]
warm_containers = "EAGER"

[preprod.local_start_lambda.parameters]
warm_containers = "EAGER"
