AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-random-no
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 60
Parameters:
  Stage:
    Type: String
    Default: uat

Resources:
  add:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/randomNo.randomNo
      Description: Add Lambda Function      
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for ${Stage} stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"